// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNn19Rmc7w8hL1wuFqMnHImfrCdxKHJzY',
    appId: '1:745299317269:web:7c7099ea1435d4d91bf41c',
    messagingSenderId: '745299317269',
    projectId: 'flutter-practise-9ac5d',
    authDomain: 'flutter-practise-9ac5d.firebaseapp.com',
    databaseURL: 'https://flutter-practise-9ac5d-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-practise-9ac5d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMtyqQRpcqQkdTZ9HP9-6WxKxAacrh5oY',
    appId: '1:745299317269:android:03b6cf2383c1fd011bf41c',
    messagingSenderId: '745299317269',
    projectId: 'flutter-practise-9ac5d',
    databaseURL: 'https://flutter-practise-9ac5d-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-practise-9ac5d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgF0jsroDxWKhhzBC3FmsfD90Zp8J5BtE',
    appId: '1:745299317269:ios:04fbe3e7b7b307681bf41c',
    messagingSenderId: '745299317269',
    projectId: 'flutter-practise-9ac5d',
    databaseURL: 'https://flutter-practise-9ac5d-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-practise-9ac5d.firebasestorage.app',
    iosBundleId: 'com.example.flutterPractise9ac5d',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgF0jsroDxWKhhzBC3FmsfD90Zp8J5BtE',
    appId: '1:745299317269:ios:04fbe3e7b7b307681bf41c',
    messagingSenderId: '745299317269',
    projectId: 'flutter-practise-9ac5d',
    databaseURL: 'https://flutter-practise-9ac5d-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-practise-9ac5d.firebasestorage.app',
    iosBundleId: 'com.example.flutterPractise9ac5d',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNn19Rmc7w8hL1wuFqMnHImfrCdxKHJzY',
    appId: '1:745299317269:web:890a8db4cc0614471bf41c',
    messagingSenderId: '745299317269',
    projectId: 'flutter-practise-9ac5d',
    authDomain: 'flutter-practise-9ac5d.firebaseapp.com',
    databaseURL: 'https://flutter-practise-9ac5d-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-practise-9ac5d.firebasestorage.app',
  );
}
